require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/making_orders", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MakingOrder. As you add validations to MakingOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MakingOrder.create! valid_attributes
      get making_orders_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      making_order = MakingOrder.create! valid_attributes
      get making_order_url(making_order)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_making_order_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      making_order = MakingOrder.create! valid_attributes
      get edit_making_order_url(making_order)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MakingOrder" do
        expect {
          post making_orders_url, params: { making_order: valid_attributes }
        }.to change(MakingOrder, :count).by(1)
      end

      it "redirects to the created making_order" do
        post making_orders_url, params: { making_order: valid_attributes }
        expect(response).to redirect_to(making_order_url(MakingOrder.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MakingOrder" do
        expect {
          post making_orders_url, params: { making_order: invalid_attributes }
        }.to change(MakingOrder, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post making_orders_url, params: { making_order: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested making_order" do
        making_order = MakingOrder.create! valid_attributes
        patch making_order_url(making_order), params: { making_order: new_attributes }
        making_order.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the making_order" do
        making_order = MakingOrder.create! valid_attributes
        patch making_order_url(making_order), params: { making_order: new_attributes }
        making_order.reload
        expect(response).to redirect_to(making_order_url(making_order))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        making_order = MakingOrder.create! valid_attributes
        patch making_order_url(making_order), params: { making_order: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested making_order" do
      making_order = MakingOrder.create! valid_attributes
      expect {
        delete making_order_url(making_order)
      }.to change(MakingOrder, :count).by(-1)
    end

    it "redirects to the making_orders list" do
      making_order = MakingOrder.create! valid_attributes
      delete making_order_url(making_order)
      expect(response).to redirect_to(making_orders_url)
    end
  end
end
