require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.xdescribe "/sales_orders", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # SalesOrder. As you add validations to SalesOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SalesOrder.create! valid_attributes
      get sales_orders_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sales_order = SalesOrder.create! valid_attributes
      get sales_order_url(sales_order)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sales_order_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      sales_order = SalesOrder.create! valid_attributes
      get edit_sales_order_url(sales_order)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SalesOrder" do
        expect {
          post sales_orders_url, params: { sales_order: valid_attributes }
        }.to change(SalesOrder, :count).by(1)
      end

      it "redirects to the created sales_order" do
        post sales_orders_url, params: { sales_order: valid_attributes }
        expect(response).to redirect_to(sales_order_url(SalesOrder.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SalesOrder" do
        expect {
          post sales_orders_url, params: { sales_order: invalid_attributes }
        }.to change(SalesOrder, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post sales_orders_url, params: { sales_order: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sales_order" do
        sales_order = SalesOrder.create! valid_attributes
        patch sales_order_url(sales_order), params: { sales_order: new_attributes }
        sales_order.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sales_order" do
        sales_order = SalesOrder.create! valid_attributes
        patch sales_order_url(sales_order), params: { sales_order: new_attributes }
        sales_order.reload
        expect(response).to redirect_to(sales_order_url(sales_order))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        sales_order = SalesOrder.create! valid_attributes
        patch sales_order_url(sales_order), params: { sales_order: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sales_order" do
      sales_order = SalesOrder.create! valid_attributes
      expect {
        delete sales_order_url(sales_order)
      }.to change(SalesOrder, :count).by(-1)
    end

    it "redirects to the sales_orders list" do
      sales_order = SalesOrder.create! valid_attributes
      delete sales_order_url(sales_order)
      expect(response).to redirect_to(sales_orders_url)
    end
  end
end
